役の判定処理の追加
tak-st/majang-yakitori pull request #42
Opened 2021-11-17 08:01 UTC by M-Reiji

## 概要

役の判定(自風牌、場風牌、三元牌)の処理を追加しました

## 補足

立直に謎のコメントを見つけたのでついでに削除しています
至らぬ点あればいつでもゆーてください。

2021-11-17 08:15 UTC, tak-st approved these changes

2021-11-17 08:39 UTC, tak-st approved these changes

2021-11-17 08:43 UTC, tak-st requested changes
風牌だが数字が違うパターンのテストが必要

2021-11-17 11:40 UTC, M-Reiji commented
風牌の数値が違う場合のテスト追加と不必要な行があったため削除しておきました

2021-11-19 04:12 UTC, M-Reiji reviewed
風牌の数値が違う場合のテスト追加と不必要な行があったため削除しておきました

2021-11-19 06:00 UTC, tak-st approved these changes

2021-11-19 06:01 UTC, M-Reiji reviewed
@tak-st 修正完了したのでチェックお願いします

2021-11-19 06:01 UTC, merged